# This is a basic workflow to help you get started with Actions

name: Compile HTML

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install jupyter
        run: sudo pip install jupyterlab

      - name: Install nbconvert
        run: sudo pip install nbconvert
      
      - name: Compile
        run: sudo bash create_html.sh
